version: '3.8'

services:
  # DATABASE: The Ledger
  postgres:
    image: postgres:16-alpine
    container_name: fintech-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Strangerthings06
      POSTGRES_DB: ledger_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ledger_db"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    ports:
      - "5432:5432"
    volumes:
      - "./infra/local/postgres_data:/var/lib/postgresql/data"

  # DATABASE: The Audit Trail
  mongodb:
    image: mongo:8.0
    container_name: fintech-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Strangerthings06
    ports:
      - "27017:27017"
    volumes:
      - "./infra/local/mongodb_data:/data/db"

  # AWS EMULATOR: SQS and S3
  localstack:
    image: localstack/localstack:3.4.0
    container_name: fintech-aws-emulator
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,s3
      - DEBUG=1
      - LOCALSTACK_ACKNOWLEDGE_ACCOUNT_REQUIREMENT=1
      - LOCALSTACK_HOST=localstack
      - ACTIVATE_PRO=0
      - DISABLE_EVENTS=1
    volumes:
      - "./infra/local/localstack:/etc/localstack/init/ready.d"
      - "./infra/local/localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  # BACKEND: NestJS API Gateway
  api:
    build: ./api
    container_name: fintech-api
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy # CHANGE THIS from service_started
      mongodb:
        condition: service_started
      localstack:
        condition: service_started
    env_file:
      - .env

  # WORKER: .NET Reconciliation Engine
  auditor:
    build: ./services/ReconciliationService
    container_name: fintech-auditor
    depends_on:
      - postgres
      - mongodb
    env_file:
      - .env