version: '3.8'

services:
  # DATABASE: The Ledger
  postgres:
    image: postgres:18-alpine
    container_name: fintech-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Strangerthings06
      POSTGRES_DB: ledger_db
    ports:
      - "5432:5432"

  # DATABASE: The Audit Trail
  mongodb:
    image: mongo:8.0
    container_name: fintech-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Strangerthings06
    ports:
      - "27017:27017"

  # AWS EMULATOR: SQS and S3
  localstack:
    image: localstack/localstack:latest
    container_name: fintech-aws-emulator
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,s3
      - DEBUG=1
      - LOCALSTACK_ACKNOWLEDGE_ACCOUNT_REQUIREMENT=1

  # BACKEND: NestJS API Gateway
  api:
    build: ./api
    container_name: fintech-api
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongodb
      - localstack
    environment:
      # We use service names (postgres, mongodb) instead of 'localhost'
      - POSTGRES_URI=postgresql://admin:Strangerthings06@postgres:5432/ledger_db
      - MONGO_URI=mongodb://admin:Strangerthings06@mongodb:27017/admin
      - SQS_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1

  # WORKER: .NET Reconciliation Engine
  auditor:
    build: ./services/ReconciliationService
    container_name: fintech-auditor
    depends_on:
      - postgres
      - mongodb
    environment:
      - PG_CONN=Host=postgres;Username=admin;Password=Strangerthings06;Database=ledger_db
      - MONGO_CONN=mongodb://admin:Strangerthings06@mongodb:27017