# Shared settings
database:
  user: admin
  pass: Strangerthings06
  ledgerName: ledger_db

images:
  postgres: postgres:16-alpine
  mongodb: mongo:8.0
  localstack: localstack/localstack:3.0.0
  api: 172786533438.dkr.ecr.us-east-1.amazonaws.com/fintech-dr-api:latest
  auditor: 172786533438.dkr.ecr.us-east-1.amazonaws.com/fintech-dr-auditor:latest